ALTER SESSION SET DATE_INPUT_FORMAT = 'DD/MM/YYYY';

--TOTAL TRANSACTIONS BY EACH BANK
SELECT
SPLIT_PART(TRANSACTION_CODE, '-', 1) AS BANK,
SUM(VALUE) AS TOTAL_VALUE,
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK01,
GROUP BY BANK;

--TOTAL VALUES BY BANK, WEEKDAY AND TRANSACTION TYPE
SELECT
SPLIT_PART(TRANSACTION_CODE, '-', 1) AS BANK,
IFF(ONLINE_OR_IN_PERSON = 1,'Online','In-Person') AS TRANSACTION_TYPE,
DAYOFWEEK(TO_DATE(SPLIT_PART(TRANSACTION_DATE, ' ', 1))) AS WEEKDAY,
SUM(VALUE) AS VALUE,
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK01,
GROUP BY BANK, TRANSACTION_TYPE, WEEKDAY
ORDER BY BANK DESC, WEEKDAY ASC;

--TOTAL VALUE BY BANK AND CUSTOMER CODE
SELECT CUSTOMER_CODE,
SPLIT_PART(TRANSACTION_CODE, '-', 1) AS BANK,
SUM(VALUE) AS VALUE
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK01
GROUP BY CUSTOMER_CODE, BANK;
