--Challenge can be found: https://preppindata.blogspot.com/2023/02/2023-week-5-dsb-ranking.html

WITH MAIN_T AS (

SELECT 
SPLIT_PART(TRANSACTION_CODE, '-', 1) AS BANK,
MONTHNAME(DATE(TRANSACTION_DATE,'dd/MM/yyyy hh24:mi:ss')) as TRANSACTION_MONTH,
SUM(VALUE) AS TOTAL_VALUE,
RANK() OVER(PARTITION BY MONTHNAME(DATE(TRANSACTION_DATE,'dd/MM/yyyy hh24:mi:ss')) ORDER BY SUM(VALUE) DESC) AS BANK_RANK_PER_MONTH 
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK01
GROUP BY BANK, TRANSACTION_MONTH
)

, AVG_RANK_PER_BANK AS (
SELECT
BANK, 
AVG(BANK_RANK_PER_MONTH ) AS AVG_RANK_PER_BANK
FROM MAIN_T
GROUP BY BANK
)

, AVG_TRANS_PER_BANK AS (
SELECT
BANK_RANK_PER_MONTH,
AVG(TOTAL_VALUE) AS AVG_TRANSACTION_VALUE_PER_RANK
FROM MAIN_T
GROUP BY BANK_RANK_PER_MONTH
)

SELECT
T.BANK,
TRANSACTION_MONTH,
TOTAL_VALUE,
T.BANK_RANK_PER_MONTH,
AT.AVG_TRANSACTION_VALUE_PER_RANK,
AR.AVG_RANK_PER_BANK
FROM MAIN_T AS T
JOIN AVG_RANK_PER_BANK AS AR ON AR.BANK = T.BANK
JOIN AVG_TRANS_PER_BANK AS AT ON AT.BANK_RANK_PER_MONTH = T.BANK_RANK_PER_MONTH
